# YAML file to create simple nginx
version : '3.7'

services :
  web :
    container_name: "web-app"
    image: 'nginx'
    volumes: 
      - "/Users/glen/Desktop/web:/usr/share/nginx/html"
    ports: 
      - "8080:80"

    
