# YAML file to create simple nginx
version : '3.7'

services :
  web :
    #container_name: "web-app"
    image: 'nginx'
    volumes: 
      - "/Users/glen/Desktop/web:/usr/share/nginx/html"
    ports: 
      - "8070-8090:80"
   
    

  mysql:
    container_name: "mysql"
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'glen'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Password@2019'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Password@2019'
    image: mysql:5.7
    ports: 
      - "3310:3306"
    volumes: 
      - "/Users/glen/Desktop/sql:/var/lib/mysql"

networks:
    default:
        external:
            name: myappnet
    
