apiVersion : v1
kind: Service
metadata:
    name: "schemakube-4b8d"
    labels:
        app: "schemakube-4b8d"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "schemakube-4b8d"
        name : "schemakube-4b8d"
